# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f7671b257d1ae391ed0409254883c57c9abf86a81daebd0880601324b7a1dfe2da06df5ba6fe1f1868e632089fdb179d924c28647bb11e689496163b4471b9b

test:
  secret_key_base: 91acd69ddf6f5c29ab096faecf7d74776274dc83169814fb2e73461b209857ae57fba4c9f3177f1e6a7281de2ca0b3727043abc7f6057eb10786f128eb5e75e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
